### ISSUE TITLE
Seems to depend upon CUDA, but not in requirements.txt file

### ISSUE THREAD

**Issue by GlazerMann** [samsledje/ConPLex#27]
This error when running:
OSError: libcurand.so.10: cannot open shared object file: No such file or directory
I think that the requirements.txt file should have cudatoolkit version specified.

**Comment by samsledje** [comment]
Hi @GlazerMann ,

Can you clarify if you are installing from source or via `pip`? It is a little tricky to specify CUDA dependencies generally since they depend on the CUDA drivers for the particular machine.

**Comment by GlazerMann** [comment]
The user in question used pip.  You are right about the dependencies.  Perhaps the make file could suggest the user have cuda installed.

**Comment by samsledje** [comment]
Is the issue fixed for the user by installing `cudatoolkit` prior to `pip install conplex-dti`? If this works, I can update the installation instructions to specify this. If not, I'll have to spend some time figuring out the best way to add torch dependency correctly to our current build process with poetry/pyproject.toml, or otherwise overhaul the build process.

**Comment by GlazerMann** [comment]
That worked for them.

**Comment by samsledje** [comment]
Great, thanks for pointing this out!
